# -*- coding: utf-8 -*-
"""validacion.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TgnnWpVddIY-n2Pz1AuEHDjzcKSIufji
"""

import pandas as pd
import matplotlib.pyplot as plt

# Cargar el archivo CSV
data = pd.read_csv('trafico_fantasma experiment-table.csv', skiprows=6)

# Limpiar los corchetes en la primera fila
data.columns = data.columns.str.replace('[\[\]]', '', regex=True)

# Agrupar los datos por el número de autos (densidad) y calcular el flujo promedio
agrupado = data.groupby('numero-de-carros').agg({'mean lista-flujo': 'mean'}).reset_index()

# Asignar variables para graficar
densidad = agrupado['numero-de-carros']
flujo = agrupado['mean lista-flujo']

# Crear la gráfica
plt.figure(figsize=(10, 6))
plt.plot(densidad, flujo, marker='o', linestyle='-')
plt.xlabel('Autos')
plt.ylabel('Flujo')
plt.grid(True)
plt.show()

# Guardar la gráfica como archivo PNG
plt.savefig('Validacion.png', dpi=300)